USE master

CREATE TABLE Tournament
(TID int NOT NULL PRIMARY KEY IDENTITY(1,1),
HOST int NOT NULL,
SIZE int NOT NULL,
TYPE int NOT NULL)

CREATE TABLE Users
(UID int NOT NULL PRIMARY KEY IDENTITY(1,1),
NAME varchar(255),
EMAIL varchar(255),
USERNAME varchar(255) NOT NULL,
PASSWORD varchar(255) NOT NULL,
BIO varchar(255))

CREATE TABLE Participant
(TID int NOT NULL FOREIGN KEY REFERENCES Tournament(TID),
UID int NOT NULL FOREIGN KEY REFERENCES Users(UID),
PLEVEL int NOT NULL,
ISACTIVE BIT NOT NULL,
CONSTRAINT PK_TID PRIMARY KEY(TID, UID))

CREATE TABLE Singles
(MID int NOT NULL,
TID int NOT NULL FOREIGN KEY REFERENCES Tournament(TID),
P1 int,
P2 int, 
P1SCRORE int,
P2SCORE int, 
WINNER int,
CONSTRAINT PK_Singles PRIMARY KEY(TID, MID))

CREATE TABLE Doubles
(MID int NOT NULL,
TID int NOT NULL FOREIGN KEY REFERENCES Tournament(TID),
T1 int,
T2 int,
T1SCORE int,
T2SCORE int,
WINNER int,
CONSTRAINT PK_Doubles PRIMARY KEY(TID, MID))

CREATE TABLE Team
(TeamID int NOT NULL PRIMARY KEY IDENTITY(1,1),
P1ID int NOT NULL,
P2ID int NOT NULL)

/*
BEGIN TRAN
DROP TABLE Doubles
DROP TABLE Singles
DROP TABLE Team
DROP TABLE Participant
DROP TABLE Tournament
DROP TABLE Users
--COMMIT
--ROLLBACK
*/